use_frameworks!

target 'StickyHeaderTabController_Example' do
  pod 'StickyHeaderTabController', :path => '../'

  target 'StickyHeaderTabController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 7.0.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
